/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Cadastrar: typeof import('./src/components/Cadastrar/index.vue')['default']
    CatalogoReceitas: typeof import('./src/components/CatalogoReceitas/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home/index.vue')['default']
    Login: typeof import('./src/components/Login/index.vue')['default']
    Receita: typeof import('./src/components/Receita/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sobre: typeof import('./src/components/Sobre/index.vue')['default']
  }
}
